### ISSUE TITLE
edit enhancements involving add/remove/update conditions

### ISSUE THREAD

**Issue by nicoalee** [neurostuff/neurostore#112]

**Comment by nicoalee** [comment]
do we ever want users to be able to delete conditions? @adelavega @jdkent

**Comment by jdkent** [comment]
I would say users can delete conditions when:
1. they own the condition
2. the condition is not being used in any other analysis

it would feel weird if person B used a condition from person A and if person A deleted the condition, Person B would no longer have that condition in their analysis.

I expect person B to still have that condition in their analysis.

**Comment by nicoalee** [comment]
> 

we might have to create some sort of global "Manage Conditions Page" then because it doesn't really make sense to handle condition management if you're editing a contrast
