### ISSUE TITLE
fix issue with cloning

### ISSUE THREAD

**Issue by nicoalee** [neurostuff/neurostore#136]

**Comment by nicoalee** [comment]
There seems to be an odd behaviour with the old frontend view appearing.
Additionally, there seems to be an error when opening studies that have been cloned.

**Comment by nicoalee** [comment]
The behavior with the old frontend appearing has to do with builds that have replaced previous ones. This is resolved.

**Comment by jdkent** [comment]
the issue with opening cloned studies with images comes from the images object not allowing there to be a null value for `add_date`. This was closed with #137, or were you talking another issue with opening studies that have been cloned?

**Comment by nicoalee** [comment]
No, it is resolved. The other issue I was referring to was the old frontend appearing, but that was due to caching on my browser. Everything looks good now
