### ISSUE TITLE
Does the Role table serve a purpose?

### ISSUE THREAD

**Issue by jdkent** [neurostuff/neurostore#138]
or is all it's functionality served by Auth0?

**Comment by adelavega** [comment]
I think it's probably subsumed by Auth0, but I don' tsee too much in leaving it in. You could try removing it, since I doubt it's doing anything but it may be an assumption of `flask-security` for it to be there

**Comment by adelavega** [comment]
Although now I'm questioning if you need `flask-security` at all given that you have `Auth0`

**Comment by jdkent** [comment]
`flask-security` may be removed, just need to change how the User table is created.

**Comment by jdkent** [comment]
still will be good to have roles for handling personal data.
