### ISSUE TITLE
Auth0: Can't change Google account

### ISSUE THREAD

**Issue by adelavega** [neurostuff/neurostore#196]
If I use Google SSO to login, then logout, then login again w/ Google, it will skip letting me choose which Google account I want to use and assume the previous one.

**Comment by jdkent** [comment]
I wonder if it would ask again if you cleared your cookies?

**Comment by adelavega** [comment]
Probably not but it still seems like it should not require that

**Comment by jdkent** [comment]
looks relevant: https://auth0.com/docs/authenticate/login/logout/log-users-out-of-idps

(but appears to log the user out of google/facebook, whatever social connection they used to log in)

**Comment by jdkent** [comment]
tested this again, appears to ask which account to select everytime, considering fixed.
