### ISSUE TITLE
add public/private button for user owned studies/datasets/annotations

### ISSUE THREAD

**Issue by jdkent** [neurostuff/neurostore#198]
add a public/private button for:
- [x] studies
- [x] datasets
- [x] annotations

**Comment by nicoalee** [comment]
We need to revisit this. When do studies/studysets/annotations become public? When a meta-analysis is run?

**Comment by jdkent** [comment]
there should be a button to make public, but by default should be private. (this has not been the case so far though)

**Comment by nicoalee** [comment]
We are now creating a private/public toggle for the entire project. This should trickle down and set certain annotations and studysets to be private/public
