### ISSUE TITLE
Should annotation columns have an explicit type?

### ISSUE THREAD

**Issue by adelavega** [neurostuff/neurostore#210]
Currently, @nicoalee is using a heuristic to determine type on the frontend where the first row's value is the correct type for a column. 

This strikes me a bit odd in that we don't explicitly have a "type" set but we assume it.

We could add a key `type` that sets the type, so that Nick doesn't have to check, and can assume the backend respects the types.

**Comment by jdkent** [comment]
this sounds like a good idea, and it's solution actually helps with another quirk of updating annotations.

Want to make sure I get this right, the relevant types are:
- [ ] number
- [ ] string
- [ ] boolean

**Comment by jdkent** [comment]
could split number into float/int, but assume number/float.

**Comment by nicoalee** [comment]
this makes sense to me

**Comment by jdkent** [comment]
closed by #212
