### ISSUE TITLE
meta-analysis studyset/annotation/specification all set to same id.

### ISSUE THREAD

**Issue by jdkent** [neurostuff/neurostore#295]
example: https://synth.neurostore.xyz/api/meta-analyses/4gM72vMrRgiW

I think at the end of the creation of the meta-analysis, the same id gets pushed to studyset/annotation/specification.

**Comment by nicoalee** [comment]
@jdkent I believe this is actually a backend issue.
In swagger, when I do the request:

NEUROSYNTH annotations /POST:
```
{
     internal_studyset_id: "89dVU52znvix",
     neurostore_id: "W8yqc57ty4b8"
}
```
the resulting response is:
```
{
  "created_at": "2022-06-03T21:32:39.484217+00:00",
  "id": "3pvn3dDmx8PA",
  "neurostore_id": "W8yqc57ty4b8",
  "snapshot": null,
  "studyset": "W8yqc57ty4b8",
  "updated_at": null,
  "user": "github|26612023"
}

```

**Comment by nicoalee** [comment]
@jdkent I get a similar issue for meta-analyses:

NEUROSYNTH meta-analyses /POST:
```
{
  "internal_annotation_id": "3pvn3dDmx8PA",
  "internal_studyset_id": "89dVU52znvix",
  "name": "aergergrt",
  "specification": "W8yqc57ty4b8"
}
```

the resulting response is:

```
{
  "annotation": "W8yqc57ty4b8",
  "created_at": "2022-06-03T21:39:20.030312+00:00",
  "description": null,
  "id": "UGdjwQGKw4GW",
  "name": "aergergrt",
  "specification": "W8yqc57ty4b8",
  "studyset": "W8yqc57ty4b8",
  "updated_at": null,
  "user": "github|26612023"
}
```

**Comment by nicoalee** [comment]
closed by accident!

**Comment by jdkent** [comment]
I think I'm having a hard time replicating with swagger:
![Screenshot from 2022-06-07 12-43-33](https://user-images.githubusercontent.com/12564882/172448398-54724846-c3f4-47b7-81cd-d1f4cab925c1.png)

input:
```
{
  "description": "string",
  "internal_annotation_id": "5VJFBFz6sQ5V",
  "internal_studyset_id": "3SS7CRbXpi3i",
  "name": "string",
  "specification": "5q9KVfNPqkhC"
}
```

output:
```
{
  "annotation": "5D7tfxDuxqAg",
  "created_at": "2022-06-07T17:43:02.175276+00:00",
  "description": "string",
  "id": "4iNNH9aw73G4",
  "name": "string",
  "specification": "5q9KVfNPqkhC",
  "studyset": "3vst5EPMeQ7T",
  "updated_at": null,
  "user": "yJziQ6gqyxZspJMTxu6p9hz0ops5KqFB@clients"
}
```

**Comment by jdkent** [comment]
Okay, I think I have a lead:

When finalizing the meta-analysis, post requests are made to:
- `/specifications`
- `/studysets`
- `/annotations`

the body of each post request:

### specifications:
```json
{"type":"CBMA","estimator":{"type":"MKDADensity","args":{"null_method":"approximate","n_iters":10000,"**kwargs":{},"kernel__r":10,"kernel__value":1}},"mask":"","contrast":"","transformer":"","corrector":{"type":"FDRCorrector","args":{"alpha":0.05,"method":"indep"}},"filter":"RH_index_finger"}
```
looks normal, and returns a response with the following "id" parameter: `{"id": "RxSNwtAonjwU"}`

### studysets
```json
{"neurostore_id":"RxSNwtAonjwU"}
```
`neurostore_id` should be `3vst5EPMeQ7T`, not the specification_id

### annotations

```json
{
    "neurostore_id": "RxSNwtAonjwU",
    "internal_studyset_id": "5kiBGBRLjtyU"
}
```

`neurostore_id` should be `5D7tfxDuxqAg`
