### ISSUE TITLE
authentication/login discussion

### ISSUE THREAD

**Issue by jdkent** [neurostuff/neurostore#34]
related to #32

![IMG_20210518_152743](https://user-images.githubusercontent.com/12564882/118882120-70735800-b8b9-11eb-86fc-c70090ca012c.jpg)
To make an analysis reproducible, you need information about the statistical model, the (MRI) data, and the software used to execute the model on the data, this information is kept in a bundle (represented in json) which is proposed to be kept on neurostore as additional information attached to a particular analysis... TODO additional explanation

![IMG_20210518_152734](https://user-images.githubusercontent.com/12564882/118882116-6ea99480-b8b9-11eb-9cdf-76fcd57dd0cb.jpg)

**Comment by adelavega** [comment]
I think our more recently discussion supersedes this so I'm closing this
