### ISSUE TITLE
add ability to delete studies

### ISSUE THREAD

**Issue by nicoalee** [neurostuff/neurostore#363]
Users can clone their own studies but are unable to delete these studies. We should add the ability to delete cloned studies

**Comment by switt4** [comment]
Along similar lines, it would also be nice to have the functionality to delete studies from an existing StudySet.  Right now the only option appears to be to create a brand new StudySet.

**Comment by nicoalee** [comment]
Thanks for the feedback! This item has been implemented and will be released in the upcoming few weeks.

**Comment by switt4** [comment]
Super.  I just started exploring neurosynth compose, so I haven't explored all of the release notes for upcoming features and fixes.
