### ISSUE TITLE
restructure user experience with meta-first approach

### ISSUE THREAD

**Issue by jdkent** [neurostuff/neurostore#381]
have users create/re-use a studyset within the context of a meta-analysis

**Comment by nicoalee** [comment]
We are going to do this by creating the concept of a "project". A project holds an associated curation board, extraction/annotation studyset, filter, and meta-analysis.
 
**curation board**
> this is where the user will import studies and filter them out based on relevancy. The modal use case is to construct a PRISMA **compliant search**
extraction/annotation studyset
> after curating studies, the user has a bunch of studies which will get ingested into neurostore. A studyset is then constructed containing these studies. The user will then go through and iteratively annotate/extract data from the papers to enter into the studyset
**filter**
> once all extraction and annotation is done, the user will then go in and select a filter that they want to select our various analyses
**meta-analysis**
> finally, the user will select the algorithm they would like to use as any other relevant data. They can then run a meta-analysis.
