### ISSUE TITLE
import from common format such as CSL-JSON, RIS, EndNote

### ISSUE THREAD

**Issue by adelavega** [neurostuff/neurostore#406]
We've used [citation.js](https://citation.js.org/) to translate between different formats before.

The idea would be to allow people to import from formats other than PubMed IDS.

These formats would presumably have complete information (e.g. author, doi, abstract), in the file itself, rather than requiring querying PubMed API. 

This would allow people to search other databases such as Scopus, etc..

**Comment by adelavega** [comment]
FWIW here's what Covidence does: 

https://support.covidence.org/help/study-imports

    EndNote XML
    PubMed text format
    RIS text format

I think EndNote XML and RIS should be sufficient, but I say we also support CSL-JSON because I like it (its a new standard that is not proprietary).

**Comment by adelavega** [comment]
just tried PsycInfo database and it can export as RIF. I think supporting just RIF and EndNote would cover 90% of use cases.

**Comment by nicoalee** [comment]
@adelavega just to confirm - would this only be for importing stubs into the identification step? Or would we potentially be able to import into any of the steps?

**Comment by adelavega** [comment]
Yes, identification

**Comment by nicoalee** [comment]
Resolved. We support import via RIS, endnote, or Bibtex formats. We also support directly pasting in pmids.
