### ISSUE TITLE
Automatically generate client typescript library from openapi spec

### ISSUE THREAD

**Issue by rwblair** [neurostuff/neurostore#41]
https://github.com/OpenAPITools/openapi-generator

We can generate a client library for the site from the speciifcation so we don't have to roll our own. I tested using typescript-fetch on the specification in the submodule commit and its almost there. Errors generated were:

Errors: 
        -attribute components.schemas.analysis.items is missing
        -attribute components.schemas.study.items is missing

Can generate the library using the --skip-validate-spec. Haven't tested importing and using the generated code yet.

@jdkent @nicoalee What do y'all think?

**Comment by jdkent** [comment]
I'm on board, I'll take a look into those errors, it may come down to a difference on how connexion interprets the spec and how the openapi tools read the spec.

**Comment by nicoalee** [comment]
i think this is a good idea especially because alejandro mentioned how the api is very simple.
One small downside - if we were to implement some CI/CD pipeline in the future. this will be an additional step to building and deploying

**Comment by nicoalee** [comment]
this seems like a good idea but unfortunately I'm running into a lot of difficulties implementing it. For starters, it seems like the generated code does not build properly. I keep getting errors:

./gen/api/configuration.ts 19:7
Module parse failed: Unexpected token (19:7)
File was processed with these loaders:
 * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
You may need an additional loader to handle the result of these loaders.
| 
| 
> export interface ConfigurationParameters {
|     apiKey?: string | Promise<string> | ((name: string) => string) | ((name: string) => Promise<string>);
|     username?: string;

https://github.com/swagger-api/swagger-codegen/issues/9712
https://github.com/swagger-api/swagger-codegen/issues/9459
https://github.com/swagger-api/swagger-codegen/issues/8024
