### ISSUE TITLE
upload workflow post meta-analysis run

### ISSUE THREAD

**Issue by nicoalee** [neurostuff/neurostore#455]
After a meta-analysis is run, we need to do a few things.
1. display the link to the resulting neurovault map
2. show the resulting coordinates
3. lock the meta-analysis specification so that it cannot be edited
4. show the status of a specification
- editable / locked AND in progress / failed / success
5. a meta-analysis may have multiple runs. We just need to show the latest run.

**Comment by nicoalee** [comment]
Specification is editable UNTIL a result exists in the results array. Once a result exists, the specification is considered locked and cannot be edited.

1. make a call to meta analysis object
 - if the reuslts array is not empty, we know that the process has at least started
3. if results array is empty, then nothing. If results array is non empty, lock the study.
4. if results array is non empty, get the id of the latest result object (should be nested). This should have a neurovault collection object id.
 - if no neurovault collection id, then its a failure state
5. if neurovault collection object 
6. 



command line tool called > download studyset, annotations, specification locally > check if studyset and annotations is already cached/snapshotted > create meta analysis result object > create neurovault collection > run meta analytic algorithm > psuh data to neurosynth compose (result object) > neurosynth-compose uploads the files to neurovault

**Comment by jdkent** [comment]
What would be useful for nick:
- show `updated_at` and `created_at` with each result object
- show all nested attributes from the result endpoint
- add neurovault_url to result view for collection_id
- add try/except to the cli runner to get a failure
  - add state attribute to result object for errors
- add neurostore_id to meta-analysis object
- add backlink from neurostore to neurosynth-compose meta-analysis and project (link to those)
- create a study and analysis neurostore_id when the meta-analysis run, not before.
-

**Comment by nicoalee** [comment]
We need to be able to configure the dev environment to point to the staging server in order to properly test this end to end,
