### ISSUE TITLE
Is it obvious the difference between Annotations and editing coordinates?

### ISSUE THREAD

**Issue by adelavega** [neurostuff/neurostore#515]
I'm a little bit concerned that most users will not know the difference between Annotations and Editing coordinates, and will find this warning confusing.

That is-- when do I need to clone a study?

Maybe we can explicitly make this obvious, or make the whole editing process more transparent?

![Screenshot from 2023-07-10 19-15-24](https://github.com/neurostuff/neurostore/assets/2774448/8dce2e1f-fd50-44e8-844c-b10fcc52c6d4)

**Comment by adelavega** [comment]
Leave informational banner (edit text), but make the Edit button become the Clone and Edit for the first time.

**Comment by nicoalee** [comment]
We no longer make a distinction between cloned and non cloned studies as visually they are the same.
