### ISSUE TITLE
Extraction phase: Can we make the list of studies more spreadsheet like?

### ISSUE THREAD

**Issue by adelavega** [neurostuff/neurostore#518]
For the list of studies in Extraction phase, it might be helpful if it was more "spreadsheet" like.

At least for very large sets of studies, its easy to get lost... Maybe we can find a slightly more information dense way of showing data, and making it obvious in the same view if a study is completed or not?

**Comment by nicoalee** [comment]
We want to represent extraction in a way that is easy to follow and that provides custom filtering for users. We have agreed on the age-old trusty tabular design filter filterable columns
