### ISSUE TITLE
Missing breadcrumbs?

### ISSUE THREAD

**Issue by adelavega** [neurostuff/neurostore#520]
I was editing a study that I cloned in the Extraction phase and I noticed the bradcrums were missing and I didn't know how to get back to the Project

![Screenshot from 2023-07-10 19-23-53](https://github.com/neurostuff/neurostore/assets/2774448/589256a2-0d30-4a5e-b29c-a451729c9f8f)

**Comment by adelavega** [comment]
It looks like maybe this study was cloned but NOT added to my Project?

**Comment by adelavega** [comment]
Yep I'm pretty sure that's what happened bc a few studies that I edited the number of studies went down from 920 to now 917 
![Screenshot from 2023-07-10 19-26-20](https://github.com/neurostuff/neurostore/assets/2774448/d734907d-bbbd-4a49-b9fc-fffe9a4a3621)

**Comment by adelavega** [comment]
In between a study being cloned and the studyset being updated succesfully the study is an orphan and the breadcrumbs are missing

**Comment by nicoalee** [comment]
related to #517
