### ISSUE TITLE
Move name and description to the end of Meta-Analysis Spec

### ISSUE THREAD

**Issue by adelavega** [neurostuff/neurostore#521]
It seems hard to give a description to an analysis spec.

Even a name is hard to give-- maybe we can auto generate?
![Screenshot from 2023-07-10 19-27-23](https://github.com/neurostuff/neurostore/assets/2774448/a078cd6a-e3a3-4527-ad16-6aa54b9d77ed)

**Comment by adelavega** [comment]
Can we make the "inclusion" column the default "selector"?

**Comment by nicoalee** [comment]
make name default to: {Project_Name} Meta Analysis: {Annotation column} (2)
