### ISSUE TITLE
warning message when importing studies

### ISSUE THREAD

**Issue by btaschler** [neurostuff/neurostore#543]
Following the tutorial: when importing studies from the PMID file, the following warning message appears: "We encountered issues importing 1 studies. You may have to create these studies manually" (see screenshot)

However, the warning doesn't specify **which study** is affected by the issue (or what the issue is). 

<img width="1267" alt="image" src="https://github.com/neurostuff/neurostore/assets/8028899/fd101c78-7fdf-4049-b507-6e2d419203b5">

**Comment by nicoalee** [comment]
resolved
