### ISSUE TITLE
dependency error in colab notebook

### ISSUE THREAD

**Issue by btaschler** [neurostuff/neurostore#551]
When running the colab notebook, I got the following NiMARE install error (see screenshot):

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. google-colab 1.0.0 requires pandas==1.5.3, but you have pandas 2.0.3 which is incompatible.`

- any way to check dependencies and/or specify requirements beforehand?
- *Note*: despite the error message, the subsequent analysis steps are still running fine (but are the results reliable?)

<br>

<img width="1491" alt="image" src="https://github.com/neurostuff/neurostore/assets/8028899/7ba44658-6867-4507-8add-fd4d6f52eaef">

**Comment by jdkent** [comment]
This incompatibility is from colab's end, so some of their functions may not work as expected, we are using very little from their package and what's important is that we are using a version of pandas that is compatible with NiMARE. Let me know if that doesn't answer your question and I will reopen
