### ISSUE TITLE
Update flavicon

### ISSUE THREAD

**Issue by nicholst** [neurostuff/neurostore#557]
I like the new neurosynth-compose logo, but when you visit https://compose.neurosynth.org/ the flavicon is a atom symbol instead of the logo.

**Comment by jdkent** [comment]
Thanks! I think the default text for react is still there too
![Screenshot from 2023-07-23 17-25-49](https://github.com/neurostuff/neurostore/assets/12564882/ffe700d7-5513-4c57-a738-60896ab51bc7)
