### ISSUE TITLE
Organization of neurostore/neurosynth APIs

### ISSUE THREAD

**Issue by jdkent** [neurostuff/neurostore#56]
How should the API endpoints on neurostore/neurosynth be organized?
- Option1:
    - neurostuff.org/store/api/v1
    - neurostuff.org/synth/api/v1
    - neurostuff.org/auth
    - Pros:
      - Keeps all applications under same domain, so JWTs authenticate under the same domain
      - Keeps the APIs (and documentation separate
      - Domain name is general purpose
    - Cons:
      - No branding recognition
      
- Option2:
  - neurosynth.org/store/api/v1
  - neurosynth.org/synth/api/v1
  - neurosynth.org/auth
  - Pros:
    - Keeps all applications under same domain, so JWTs authenticate under the same domain
    - Keeps the APIs separate
    - Domain name leverages branding from neurosynth
  - Cons:
    - People may not recognize neurostore as being general purpose
    
- Option 3:
  - neurostore.org/api/v1
  - neurosynth.org/api/v1
  - Pros:
    - Most modular design/separation of services
  - Cons:
    - Cross domain authentication is hard
    
- Option 4
  - neurostuff.org/store/api/v1
  - neurostuff.org/auth/api/v1
  - neurosynth.org/api/v1
  
  Under this division, Store and Synth would keep separate User tables with joint identities. 
  Users would got to `/auth` and get JWT which store and auth can both authenticate.
  We can look into making `/auth` a proper authentication service. 
  - Pros:
    - Let's neurostore be a separate service from neurosynth branding, and allows for a generic authentication service 
  - Cons:
    - Potential CORS issues (can hide this from user though)

**Comment by adelavega** [comment]
I vote Option 2

**Comment by nicoalee** [comment]
i think option 2 would be the best.

**Comment by adelavega** [comment]
After discussion, we are leaning towards Option4

**Comment by adelavega** [comment]
Suggestion from 7/22/21 meeting:

neurosynth.org/ -- frontend --- unified service that uses neurosynth api and neurstore api-- branding for neurostore could be included at times to make it clear where data is coming from

neurosynth.org/api -- neurosynth API -- meta-analysis specification
neurostore.org/api -- neurostore API -- study viewing and editing
neurostore.org/ -- currently no frontend for neurostore API, but could have one in the future. in the meantime can use neurosynth.org
 
all are independently authenticated through an Auth0 service that we can call:
neurokey.org
neuroid.org
could have a basic static page to represent this

neuroquery.org will remain separate for the time being 

nimare is independent python library which neurosynth.org uses and clearly identifies as such

we can describe and document the landscape of open meta-analysis tools in a collaborative documentation project 
neurostuff / neurodepot / neurostation -- a living jupyter book which gives a more high level overview of the landscape, how to use them and is more educational is nature.

**Comment by jdkent** [comment]
closing for cleaning up, feel free to re-open
