### ISSUE TITLE
internal server error when source is set

### ISSUE THREAD

**Issue by nicoalee** [neurostuff/neurostore#575]
When source is set to anything (neurovault, neuroquery, pubmed, ... etc) then we get a 500 error from the BE

![show](https://github.com/neurostuff/neurostore/assets/26612023/a2cabfef-23f1-487f-9df9-a9d4ffc7c185)

**Comment by jdkent** [comment]
oops, I should disallow using source on the base-study endpoint since it does not make sense isolate source because a base study could have multiple versions where each comes from a different source, to get source info I'll fix the info parameter for base_studies

**Comment by nicoalee** [comment]
cool, thanks james!

**Comment by nicoalee** [comment]
Source property has been removed from `/base-studies` via #573
