### ISSUE TITLE
google analytics not displaying page specific hits

### ISSUE THREAD

**Issue by nicoalee** [neurostuff/neurostore#593]
Currently, we use gtag in order to send our data to google analytics. 
`            
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', '...');
`

It doesn't currently register if a user hits a certain page. We need to modify this so that we know which page the user visits.
https://www.analyticsmania.com/post/single-page-web-app-with-google-tag-manager/
Note: this may be easier if we use react-ga4: https://www.npmjs.com/package/react-ga4

**Comment by nicoalee** [comment]
i forget: @adelavega: do we need to be concerned about GDPR stuff?

**Comment by adelavega** [comment]
I'm actually not sure. Does Google have any guidance on this?

It might not be a bad idea to look into it, although I'm hoping the use of
services makes it easier.

I think we don't use cookies so at least there's that

**Comment by nicoalee** [comment]
https://stackoverflow.com/questions/11198869/to-track-clicks-on-a-div-using-google-analytics

**Comment by nicoalee** [comment]
It seems like google analytics does not conform to GDPR standards. We will have to ask the user manually if they will accept tracking cookies and prevent their usage if not.
