### ISSUE TITLE
Misc Extraction phase feedback

### ISSUE THREAD

**Issue by adelavega** [neurostuff/neurostore#622]
I think splitting up "StudySet creation" and "ingestion" as something users have to think about too much is a bit confusing tbh. 

Here's my suggested changes to simplify this. 

**Create StudySet**

You finished Curation and selected the studies you want to include in your meta-analysis.

Now, in Extraction, you will add or edit study data, including coordinates and metadata, and add annotations to identify target analyses (i.e. contrasts) to include in your meta-analysis.

First, let's create a new StudySet to store your studies." (I think it's obvious you have to give it a name at this point)

Rename Button to "Next"

**Define Annotations** (I almost wonder if we could skip this entirely for now.... )

[Annotations](https://neurostuff.github.io/compose-docs/guide/walkthrough/Project/Extraction#annotations) allows you to associate custom values to [analyses](https://neurostuff.github.io/compose-docs/guide/glossary#analysis) within a study.

Annotations are most commonly used to select target [analyses](https://neurostuff.github.io/compose-docs/guide/glossary#analysis) for inclusion into a meta-analysis. For example, to exclude "control" contrasts and only focus on the key contrasts of interest. They may also be used to specify participant groups (i.e. patients vs controls) or any other relevant variable.

An "included" annotation is automatically created, which includes all analyses by default. 

This step is optional, you can always add Annotations later. 

Rename Button to "Next"

**Ingest**

Now, we will ingest your studies into the StudySet. 

If you have added any new Studies, they will be created in NeuroStore for you. 

This can take a few seconds or minutes depending on how many studies you selected. 

[Maybe we can say something about selecting matching studies, but with NeuroStore search this doesn't apply because it auto matches]

**Comment by adelavega** [comment]
Okay, I think splitting up StudySet creation and ingestion into two steps to tell users is confusing.

I think we should maybe first just do a single step of creation & ingestion, or at least present it as such to users. 

"Your studyset has been created - let's specify your [annotations.](https://neurostuff.github.io/compose-docs/guide/walkthrough/Project/Extraction#annotations)" --- I find this a bit confusing, I almost wonder if this should come after ingestion and be optional?

**Comment by adelavega** [comment]
I wonder if clicking the checkmark at the top right should just clear out the current study and advance?

It's not super obvious what to do here, tbh

**Comment by adelavega** [comment]
I think it could be more obvious that only one version is available and it's already selected.

![image](https://github.com/neurostuff/neurostore/assets/2774448/99017a38-0043-4543-9192-ed198f8650ce)

**Comment by adelavega** [comment]
It's not super clear how to advance from "Extraction" phase

**Comment by adelavega** [comment]
Are you sure you want to mark all the studies as complete?

Any studies you have not reviewed or annotated may have incomplete data.

**Comment by nicoalee** [comment]
curation to extraction dialog - two wizard steps. 1 to explain what is going on, and 2 to then just show a loader with some explanation text

**Comment by nicoalee** [comment]
add next and previous study buttons in the toolbar
