### ISSUE TITLE
meta-analysis specification feedback

### ISSUE THREAD

**Issue by adelavega** [neurostuff/neurostore#623]
"Select the annotation column to for inclusion. This will determine which analyses are used for this meta-analyses.

By default the "included" column includes all studies & analyses. 

At the moment, only boolean annotations are supported. "

I wonder if we should only allow boolean annotations for now if that's the case?

**Comment by adelavega** [comment]
This seems wrong:

"0 studies |229 analyses |0 coordinate"

**Comment by nicoalee** [comment]
Set default estimator option to be MKDA Density.
