### ISSUE TITLE
comments on public meta-analysis viewing

### ISSUE THREAD

**Issue by adelavega** [neurostuff/neurostore#640]
couple issues/bugs:

meta-analysis page:
- show meta-analysis user
- show studyset summary and make it clickable for more details
- no need to show annotation ID

When viewing a public studyset, there is a list of annotation
- a bit strange to see the owner of the annotation. i suppose you culd make an annotation on someone else's studyset but it will be rare. maybe only show user if its not the same user and studyset?

other studyset issues:
- show studyset user
- when you click a studyset annotation it says:
"There are no analyses to annotate. Get started by adding analyses to your studies."

**Comment by nicoalee** [comment]
we should just remove public studysets - it adds no value to our app and i dont think users will ever need it

**Comment by nicoalee** [comment]
completed as we removed public studysets page. We can reopen this in the future if we want it back
