### ISSUE TITLE
improve local storage saving of current tab

### ISSUE THREAD

**Issue by nicoalee** [neurostuff/neurostore#649]
In the extraction phase, the tab that is last visited by the user is saved in local storage. This means that if the user views a study and goes back, they land back on that same tab (e.g. saved for later).

However, this is singly set for all projects and so if you clicked "COMPLETED" for example in one project and then created a new project, you would land on COMPLETED when moving to the extraction phase instead of UNCATEGORIZED. We should update this behavior so that we save the placeholders for each project in local storage as KVPs.

**Comment by adelavega** [comment]
It might be a good quick hack to reset this to "Uncategorized" when you move to Extraction phase, to prevent user confusion
