### ISSUE TITLE
ux suggestion: show more journal details (w/o editing), in Extraction

### ISSUE THREAD

**Issue by adelavega** [neurostuff/neurostore#656]
Instead of fully collapsing all details, we can show some (even at the top?), to help orient users?

For example, when adding finger tapping, I realized I don't have access to a specific journal, so no use clicking through to PubMed. If I could see that easier, i would just skip study.

**Comment by adelavega** [comment]
also, can we make the external links open new window instead of new tab?

**Comment by jdkent** [comment]
top issue closed by #672

**Comment by nicoalee** [comment]
@adelavega closing this as from what i understand, clicking on a link (using `<a href="https://open-in-new-page.com" target="_blank">link</a>`) only tells the browser to open a new page. How the browser does this (via new tab vs new window) is not under our control and is changed via user preference in the OS.
