### ISSUE TITLE
ux bug: adding new analysis to someone else's study

### ISSUE THREAD

**Issue by adelavega** [neurostuff/neurostore#657]
when you add a new analysis to someone else's study, the annotations are incorrect. only shows the new analysis that is created, and now any existing analyses.

if you refresh (i.e. switch away and back), the data is correct.

**Comment by adelavega** [comment]
Fixed in prod

**Comment by nicoalee** [comment]
This was resolved in this issue: https://github.com/neurostuff/neurostore/issues/642
