### ISSUE TITLE
ux bug: no annotation for neurosynth analysis

### ISSUE THREAD

**Issue by adelavega** [neurostuff/neurostore#658]
![Screen Shot 2024-01-10 at 6 13 07 PM](https://github.com/neurostuff/neurostore/assets/2774448/5a545386-4720-4b1b-8c52-a68a8e13069a)

**Comment by adelavega** [comment]
Okay turns out this is a MAJOR bug.

When you switch studies, sometimes it will delete the annotation for other studies. So it's effectively impossible to include studies into your meta-analysis right now, if you switch from someone else's verison to your own

**Comment by jdkent** [comment]
This may actually be related to something that should change in the backend, let me take a look.

**Comment by adelavega** [comment]
Looks like this was closed with #648 

Closing for now
