### ISSUE TITLE
ux: incomplete pubmed ingestion

### ISSUE THREAD

**Issue by adelavega** [neurostuff/neurostore#666]
I noticed that for studies not in Neurostore, ingestion from PubMed is incomplete.

Data such as Journal and year of publication is missing, which makes it more difficult to complete `Extraction` phase

**Comment by adelavega** [comment]
@jdkent I think this is a high priority issue, as it makes it very difficult to sort through studies 

it also seems like potentially an easy fix to just keep track of authors and year when we do the intial pubmed api query.

can you put this on your todo for early this week?

**Comment by jdkent** [comment]
Just to be clear, there is complete information during curation, it's moving from curation to ingestion where this information is lost?

**Comment by adelavega** [comment]
I actually think he's just never fetching that info
