### ISSUE TITLE
Terms and Conditions

### ISSUE THREAD

**Issue by jdkent** [neurostuff/neurostore#745]
# Neurosynth Compose Website - Terms and Conditions

Welcome to Neurosynth Compose! These Terms and Conditions govern your use of the Neurosynth Compose website (hereinafter referred to as "the Website"). Please read these terms carefully before using the Website.

Acceptance of Terms: By accessing or using the Website, you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the Website.

Description of Service: Neurosynth Compose provides a platform for users to create accounts and upload neuroscience data for public use. Users may upload data, including but not limited to neuroimaging data, metadata, and associated information.

User Accounts: In order to use certain features of the Website, you may be required to create an account. You are responsible for maintaining the confidentiality of your account and password and for restricting access to your account. You agree to accept responsibility for all activities that occur under your account.

User Responsibilities: By uploading data to the Website, you represent and warrant that you have the right to do so and that the data does not infringe upon the intellectual property rights or privacy rights of any third party. You agree not to upload any data that is unlawful, defamatory, obscene, or otherwise objectionable.

Intellectual Property: Users retain ownership of the data they upload to the Website. By uploading data, users grant Neurosynth Compose a non-exclusive, royalty-free, worldwide license to use, reproduce, modify, distribute, and display the data for the purposes of operating and improving the Website.

Privacy: Neurosynth Compose respects the privacy of its users. Please review our Privacy Policy [link to privacy policy] to understand how we collect, use, and disclose information.

Limitation of Liability: Neurosynth Compose shall not be liable for any indirect, incidental, special, or consequential damages arising out of the use or inability to use the Website.

Indemnification: You agree to indemnify and hold harmless Neurosynth Compose and its affiliates, officers, agents, and employees from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of your use of the Website, your violation of these Terms and Conditions, or your violation of any rights of another party.

Modifications to Terms: Neurosynth Compose reserves the right to modify these Terms and Conditions at any time without prior notice. Your continued use of the Website after any such changes constitutes your acceptance of the new Terms and Conditions.

Governing Law: These Terms and Conditions shall be governed by and construed in accordance with the laws of [insert jurisdiction]. Any dispute arising out of or relating to these terms shall be subject to the exclusive jurisdiction of the courts located in [insert jurisdiction].

Contact Information: If you have any questions or concerns about these Terms and Conditions, please contact us at [neurosynthorg@gmail.com](mailto:neurosynthorg@gmail.com).

By using the Neurosynth Compose website, you agree to abide by these Terms and Conditions. Thank you for using Neurosynth Compose!

# Neurosynth Compose Website - Privacy Policy

This Privacy Policy describes how Neurosynth Compose ("we", "us", or "our") collects, uses, and discloses information when you use the Neurosynth Compose website (the "Website").

Information We Collect:

a. User-Provided Information: When you create an account on the Website, we collect information such as your username, email address, and any other information you choose to provide.

b. Uploaded Data: When you upload data to the Website, including neuroimaging data and associated metadata, we collect and store this information.

c. Automatically Collected Information: We may automatically collect certain information about your device and usage of the Website, including your IP address, browser type, operating system, and pages visited.

Use of Information:

a. We use the information we collect to operate and improve the Website, including providing personalized content and recommendations.

b. Uploaded data may be made publicly accessible for academic and research purposes, in accordance with the terms and conditions of the Website.

c. We may use your email address to send you administrative communications, such as account notifications and updates to our terms and policies.

Disclosure of Information:

a. We may disclose your information to third-party service providers who assist us in operating the Website, subject to confidentiality agreements.

b. Uploaded data may be shared publicly on the Website or with other users for academic and research purposes.

c. We may disclose information in response to a subpoena, court order, or other legal process, or to protect our rights or the rights of others.

Data Retention:

We retain the information we collect for as long as necessary to fulfill the purposes outlined in this Privacy Policy, unless a longer retention period is required or permitted by law.

Security:

We take reasonable measures to protect the security of your information, but please be aware that no method of transmission over the internet or electronic storage is completely secure.

Your Choices:

You may update or delete your account information at any time by logging into your account settings. Please note that certain information may be retained in our backup systems for a limited period of time.

Third-Party Links:

The Website may contain links to third-party websites or services that are not owned or controlled by us. We are not responsible for the privacy practices or content of these third-party sites.

Children's Privacy:

The Website is not intended for children under the age of 13, and we do not knowingly collect personal information from children under 13. If you believe that we have inadvertently collected information from a child under 13, please contact us immediately.

Changes to this Privacy Policy:

We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.

Contact Us:

If you have any questions or concerns about this Privacy Policy, please contact us at [neurosynthorg@gmail.com](mailto:neurosynthorg@gmail.com).

By using the Neurosynth Compose website, you consent to the collection, use, and disclosure of your information as described in this Privacy Policy. Thank you for using Neurosynth Compose!

**Comment by jdkent** [comment]
I literally just used chatGPT to generate this, I've read it over and it looks reasonable, but please check it over as well.

**Comment by nicoalee** [comment]
where are we hosting this text?
