### ISSUE TITLE
crossref API requests are slow/rate limited

### ISSUE THREAD

**Issue by jdkent** [neurostuff/neurostore#798]
When I download the studyset as a bibtex file, the crossref API quickly gets ratelimited (429 too many requests), what information are we getting from crossref that we don't need when downloading as a csv, which is pretty much instantaneous.

**Comment by nicoalee** [comment]
try adding a rate limit to cross ref. if that doesnt work well or takes too long, then we can just get rid of crossref entirely.

**Comment by nicoalee** [comment]
closed by https://github.com/neurostuff/neurostore/pull/802
